#!/bin/sh

for I in uncompressed/*.dat; do
	BASE=$(basename "$I" | sed 's/\.dat$//')

	echo "$BASE.lz4"
	lz4 -9 <$I >compressed/$BASE.lz4

	echo "$BASE.zlib"
	ruby -e 'require "zlib"; $stdout.write(Zlib::deflate($stdin.read))' <$I >compressed/$BASE.zlib

	echo "$BASE.lzma"
	xz --format=lzma <$I >compressed/$BASE.lzma

	echo "$BASE.xz"
	xz --format=xz <$I >compressed/$BASE.xz

	echo "$BASE.lzma_raw"
	xz --format=raw <$I >compressed/$BASE.lzma_raw

	echo "$BASE.lz4"
	lz4 --best -BD <$I >compressed/$BASE.lz4

	echo "$BASE.br"
	brotli -f -o compressed/$BASE.br $I

	echo "$BASE.zst"
	zstd --ultra -22 -f -o compressed/$BASE.zst --format=zstd $I

	echo "$BASE.lzham"
	lzhamtest -m4 -d29 -u -x -o -e -h0 c $I compressed/$BASE.lzham
done
